Reapply changes which were reverted

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -13,7 +13,7 @@ on:
 jobs:
   phpunit:
     # We don't want the scheduled jobs to run on forks of Mautic
-    if: (github.event_name == 'schedule' && github.repository_owner == 'mautic') || (github.event_name != 'schedule')
+    if: (github.event_name == 'schedule' && (github.repository == 'mautic/mautic' || github.repository == 'mautic/api-library') ) || (github.event_name != 'schedule')
     runs-on: ubuntu-latest
 
     strategy:
@@ -56,6 +56,13 @@ jobs:
         coverage: pcov
         ini-values: pcov.directory=., pcov.exclude="~tests|themes|vendor~"
     
+    - name: add MySQL config file
+      run: |
+        mysqldump --version
+        mysqldump --print-defaults
+        cp .github/ci-files/.my.cnf ~/.my.cnf
+        mysqldump --print-defaults
+
     - name: Set SYMFONY_ENV to test
       run: echo "SYMFONY_ENV=test" >> $GITHUB_ENV
 
@@ -104,7 +111,7 @@ jobs:
         composer test -- plugins/MauticCrmBundle/Tests/Pipedrive
 
     - name: Upload coverage report
-      if: ${{ matrix.php-versions == '7.4' && matrix.db-types == 'mysql' }}
+      if: ${{ matrix.php-versions == '7.4' && matrix.db-types == 'mysql' && github.repository == 'mautic/mautic'}}
       uses: codecov/codecov-action@v2
       with:
         files: ./coverage.xml
@@ -126,13 +133,13 @@ jobs:
 
   misc:
     # We don't want the scheduled jobs to run on forks of Mautic
-    if: (github.event_name == 'schedule' && github.repository_owner == 'mautic') || (github.event_name != 'schedule')
+    if: (github.event_name == 'schedule' && (github.repository == 'mautic/mautic' || github.repository == 'mautic/api-library') ) || (github.event_name != 'schedule')
     runs-on: ubuntu-latest
 
     strategy:
       fail-fast: false
       matrix:
-        commands: ['PHPSTAN', 'CS Fixer', 'Rector']
+        commands: ['PHPSTAN', 'CS Fixer', 'Rector', 'scaffolded files mismatch', 'PHPStan baseline changes']
 
     name: ${{ matrix.commands }}
 
@@ -170,6 +177,27 @@ jobs:
           done
           if [[ $cs_fix_files ]]; then
             bin/php-cs-fixer fix --config=.php-cs-fixer.php -v --dry-run --using-cache=no --show-progress=dots --diff $cs_fix_files
+          fi
+        elif [[ "${{ matrix.commands }}" == "scaffolded files mismatch" ]]; then
+          wget -q -O /tmp/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod 755 /tmp/jq
+          /tmp/jq -r '.extra["mautic-scaffold"]["file-mapping"] | to_entries[] | "diff -q \(.key | sub("\\[(project|web)-root\\]";".")) app/\(.value)"' app/composer.json > diff_commands.sh
+          bash diff_commands.sh | tee /tmp/diff_command_output.txt
+          rm diff_commands.sh
+          if [[ $(wc -l </tmp/diff_command_output.txt) -ge 1 ]]; then
+            echo "some scaffolded files were not updated"
+            echo "Please apply the same changes in the files mentioned above"
+            exit 1
+          fi
+        elif [[ "${{ matrix.commands }}" == "PHPStan baseline changes" ]]; then
+          if [[ "${{ steps.changed-files.outputs.modified_files }}" == *"phpstan-baseline.neon"* ]]; then
+            stat=$(git diff --shortstat "origin/${{ github.base_ref }}" ${{ github.sha }} -- phpstan-baseline.neon)
+            echo $stat
+            regex="[0-9]+[[:space:]]insertion"
+            if [[ $stat =~ $regex ]]; then
+              echo "There are modifications (added or changed lines) to the phpstan-baseline.neon"
+              echo "Please fix the PHPStan errors instead of altering the baseline file"
+              exit 1
+            fi
           fi
         else
           echo "Invalid command"
